---
AllCops:
  NewCops: enable
  SuggestExtensions:
    rubocop-rake: false

Style/Documentation:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes


